project:
  type: book
  output-dir: ../mikaelbrunila.com/public/information-theory

book:
  title: "From Bits to Embeddings – A Critical Introduction to Information Theory"
  chapters:
    - part: "Part I — Introduction"
      chapters:
        - index.qmd
    - part: "Part II — Information Theory"
      chapters:
        - notebooks/01_bits.ipynb
        - notebooks/02_entropy.ipynb
        - notebooks/03_kl_divergence.ipynb
    - part: "Part III — Language Models (TBD)"
      chapters:
        - notebooks/04_word2vec.ipynb
        - notebooks/05_attention.ipynb

format:
  html:
    monofont: "JetBrains Mono"
    code-overflow: scroll
    css: styles.css
    include-in-header: hide-html-code.html
    include-after-body: footer.html
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 4
    math: mathjax
    code-fold: show
    code-summary: "Code Toggle"
    open-graph: true
    twitter-card: true
    image: img/shannon_general_communication_system_diagram.png
    description: "A comprehensive introduction to classical information theory as conceived by Claude Shannon and its connections to neural networks and large language models today."

execute:
  freeze: false
  cache: true